# Generated by Django 5.2 on 2025-05-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
    ]
