# Generated by Django 5.2 on 2025-05-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(default=list),
        ),
    ]
