# Generated by Django 5.2 on 2025-05-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='productprice',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
