# Generated by Django 5.2 on 2025-05-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_productprice_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='discount_percent',
        ),
    ]
