# Generated by Django 5.2 on 2025-05-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_method',
            field=models.CharField(default='COD', max_length=100),
            preserve_default=False,
        ),
    ]
