# Generated by Django 5.2 on 2025-05-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_shippingaddress_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
